### ISSUE TITLE
GitHub Stats

### ISSUE THREAD

**Issue by soiqualang** [ethernal-serenade/ethernal-serenade#1]
Thay vì dùng tấm hình, em có thể dùng cái này để nó tự update nè

![Ethernal-Serenade's github stats](https://github-readme-stats.vercel.app/api?username=Ethernal-Serenade&show_icons=true)

Xem thêm
https://dothanhlong.org/advanced-formatting-in-github-markdown/

**Comment by Ethernal-Serenade** [comment]
Oke anh... tại không biết nó có hiển thị cái hình lun hay không á hihi
